### ISSUE TITLE
RuntimeError: Memory access out of bounds

### ISSUE THREAD

**Issue by thanieljay** [DeepARSDK/quickstart-web-js#2]
Tried to run the sample this SDK to a nginx web server but unfortunately it's not working. I got this errors.

exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[3119]:0x106c9c
    at <anonymous>:wasm-function[1920]:0x7b2e7
    at dynCall_v (<anonymous>:wasm-function[2216]:0x8905b)
    at Object.e.dynCall_v (http://128.199.178.170/lib/deepar.js:227:359)
    at Ob.g (http://128.199.178.170/lib/deepar.js:80:327)
    at Lb (http://128.199.178.170/lib/deepar.js:82:61)

    deepar.js:82 Uncaught RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[3119]:0x106c9c
    at <anonymous>:wasm-function[1920]:0x7b2e7
    at dynCall_v (<anonymous>:wasm-function[2216]:0x8905b)
    at Object.e.dynCall_v (http://128.199.178.170/lib/deepar.js:227:359)
    at Ob.g (http://128.199.178.170/lib/deepar.js:80:327)
    at Lb (http://128.199.178.170/lib/deepar.js:82:61)

    006465ce:1 Uncaught RuntimeError: memory access out of bounds
    at _malloc (<anonymous>:wasm-function[437]:0x7234)
    at e._malloc (http://128.199.178.170/lib/deepar.js:225:111)
    at http://128.199.178.170/lib/deepar.js:152:34
    at http://128.199.178.170/lib/deepar.js:96:280
    at XMLHttpRequest.d.onload (http://128.199.178.170/lib/deepar.js:53:74)

**Comment by SGoerzen** [comment]
It happened to me, when I accedently loaded a png file into loadEffect function. You can try to check what file you provide into loadEffect.
Maybe it is not accessible or sth. like this?

**Comment by faychan** [comment]
Did you find a solution? I also have the exact same bug in ReactJS

**Comment by Sikter** [comment]
Have you checked if your content metadata (mainly Content-Encoding and Content-Type) is correct for filters or DeepAR SDK files. For filters we usually use this configuration
Content-Encoding: gzip (or br)
Contnet-Type: binary/octet-stream

You can inspect our demos at https://deepar.ai/demos.

Hope this helps.

**Comment by beri-sela** [comment]
> Did you find a solution? I also have the exact same bug in ReactJS @thanieljay

I have the same bug in ReactJS. Were you able to make it work?

**Comment by JelenaKB** [comment]
This issue happens when the metadata headers settings (Content-Encoding and Content-Type) for .js, .wasm, model and effect files on your server are incorrectly set. 

You should compare your settings to the ones in our demos https://deepar.ai/demos.
